language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
script: npm run build
# deploy:
#   on: master
#   provider: heroku
#   app: build-and-deploy_2018
#   api_key:
#     secure: f5307om+3bFsQ7Os+kjVCNZCiSr+7aCbUMbf1Ivn99lFJumVsAJVTQomM/v3ayXSAARN0UN7URPKuBNYKhcwTEvFWunRU66H9pUJ7IDXyxilfJJ91R6bcs69yerksnoZtfKcI2gxZF1AhfwofyjYSnuvScHiMU435VPUPWiBpPYn0inwqNrFTCb+TWfUiyaeLPbCxRYlFpdvvLv/jCZEuWMDuDZN5v7YoDWLSg4+Hd5+pb4/6xyc0E5a5pUoNEbmqHMsOoS72LGfmYUfSr5LXPF5K4QDzPc4ZpAVUq6mGDCkleZaSkPup6O82LVO5X8XZbPpayHrvhXEO/JCOdnq57GxJ46UbIEI2GiWM+l2OAXL44D24BsoPmzy64TtWKp+b3FHROQQzTEIrmIxeA+OSuU8tJMJl7aI7L9/sM6vYqC+74HA9MvOZNd95LK39NSTk8BDzMru7TVqDb+8Xtmo1pjy7Ets79h+pm170vqoFVLpKd1YFiWhKyEuj7x9M2igZ0Q9APleW3i7/162WcszLdX0qLnXfappXuhWKDJS6omxD1+4ticQTQ3+IXwZwcIu4cshj2CaR4wokUTPywJmOZmUdopmyoYvq+bFiKKxtHWA+n/X3B+LCRsPbQIyLrkDHf/YBI/1+FV/IKj9nFzE5sO42mFNkniu6PM8mGQUR8U=
#   skip_cleanup: true
